### ISSUE TITLE
problem with ascii.live

### ISSUE THREAD

**Issue by hc12-pl** [hugomd/ascii-live#40]
when i want to type `curl ascii.live/parrot` is says "Moved Permanently"

**Comment by GavinGoGaming** [comment]
yeah what

**Comment by hugomd** [comment]
Sorry about this, I made some changes to the proxy that sits in front of ascii.live.

`curl -L ascii.live` should work for now as an alternative.

**Comment by hugomd** [comment]
I've updated the proxy, this should be fixed now.
